version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  docs:
    build: .
    command: mkdocs serve -a 0.0.0.0:9001
    volumes:
      - .:/code
    working_dir: /code/docs/
    ports:
      - "9001:9001"
    depends_on:
      - web
